### ISSUE TITLE
Fix CVE 

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/db-fundamentals-java#7]
## Problem 

Currently, the build is broken because of a detected CVE in the dependencies. We need to check the CVE and remove the dependency if possible.

**Comment by pj-spoelders** [comment]
I remembered seeing this error before as JB briefly discussed it with me a while back so I contacted him:
Using `mvn dependency:tree ` we quickly spotted the offending dependency and we were able to remove it since it wasn't being used (junit platform).
